init_config:

instances:
  - host: localhost
    user: datadog
    pass: Dd1!
     port: 3306
 
  options:
       replication: false
       galera_cluster: false
       extra_status_metrics: true
       extra_innodb_metrics: true
       schema_size_metrics: false
       disable_innodb_metrics: false
       extra_performance_metrics: true

logs:
    - type: file
      path: /var/log/mysql/mysql_error.log
      source: mysql
      sourcecategory: database
      service: myapplication

    - type: file
      path: /var/log/mysql/mysql-slow.log
      source: mysql
      sourcecategory: database
      service: myapplication

    - type: file
      path: /var/log/mysql/mysql.log
      source: mysql
      sourcecategory: database
      service: myapplication
